import {
  TMDBMovie,
  TMDBTVShow,
  TMDBSeasonDetail,
  TMDBCredits,
  TMDBGenre,
} from "@/types/tmdb";

export const FALLBACK_GENRES: { movie: TMDBGenre[]; tv: TMDBGenre[] } = {
  movie: [
    { id: 28, name: "Action" },
    { id: 12, name: "Adventure" },
    { id: 16, name: "Animation" },
    { id: 35, name: "Comedy" },
    { id: 80, name: "Crime" },
    { id: 18, name: "Drama" },
    { id: 14, name: "Fantasy" },
    { id: 27, name: "Horror" },
    { id: 878, name: "Sci-Fi" },
    { id: 53, name: "Thriller" },
  ],
  tv: [
    { id: 10759, name: "Action & Adventure" },
    { id: 16, name: "Animation" },
    { id: 35, name: "Comedy" },
    { id: 80, name: "Crime" },
    { id: 18, name: "Drama" },
    { id: 10765, name: "Sci-Fi & Fantasy" },
    { id: 9648, name: "Mystery" },
  ],
};

export const FALLBACK_MOVIES: TMDBMovie[] = [
  {
    id: 157336,
    title: "Interstellar",
    original_title: "Interstellar",
    overview:
      "The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.",
    poster_path: "/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    backdrop_path: "/xJHokMbljvjADYdit5fK5VQsXEG.jpg",
    release_date: "2014-11-05",
    vote_average: 8.4,
    vote_count: 35400,
    popularity: 145.2,
    adult: false,
    genre_ids: [12, 18, 878],
    runtime: 169,
    tagline: "Mankind was born on Earth. It was never meant to die here.",
    genres: [
      { id: 12, name: "Adventure" },
      { id: 18, name: "Drama" },
      { id: 878, name: "Sci-Fi" },
    ],
  },
  {
    id: 27205,
    title: "Inception",
    original_title: "Inception",
    overview:
      "Cobb, a skilled thief who steals corporate secrets through dream-sharing technology, is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster.",
    poster_path: "/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg",
    backdrop_path: "/s3TBrRGB1iav7gFOCNx3H31MoES.jpg",
    release_date: "2010-07-15",
    vote_average: 8.36,
    vote_count: 36200,
    popularity: 128.4,
    adult: false,
    genre_ids: [28, 878, 12],
    runtime: 148,
    tagline: "Your mind is the scene of the crime.",
    genres: [
      { id: 28, name: "Action" },
      { id: 878, name: "Sci-Fi" },
      { id: 12, name: "Adventure" },
    ],
  },
  {
    id: 872585,
    title: "Oppenheimer",
    original_title: "Oppenheimer",
    overview:
      "The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II, exploring the profound moral dilemmas and geopolitical consequences that reshaped humanity.",
    poster_path: "/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    backdrop_path: "/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg",
    release_date: "2023-07-19",
    vote_average: 8.1,
    vote_count: 9200,
    popularity: 180.5,
    adult: false,
    genre_ids: [18, 36],
    runtime: 180,
    tagline: "The world forever changes.",
    genres: [
      { id: 18, name: "Drama" },
      { id: 36, name: "History" },
    ],
  },
  {
    id: 693134,
    title: "Dune: Part Two",
    original_title: "Dune: Part Two",
    overview:
      "Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a warpath of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe.",
    poster_path: "/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg",
    backdrop_path: "/xOMo8BRK7PfcJv9JCnx7s5200bm.jpg",
    release_date: "2024-02-27",
    vote_average: 8.2,
    vote_count: 5600,
    popularity: 210.8,
    adult: false,
    genre_ids: [878, 12],
    runtime: 166,
    tagline: "Long live the fighters.",
    genres: [
      { id: 878, name: "Sci-Fi" },
      { id: 12, name: "Adventure" },
    ],
  },
  {
    id: 155,
    title: "The Dark Knight",
    original_title: "The Dark Knight",
    overview:
      "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets.",
    poster_path: "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    backdrop_path: "/dqK9Hag1054tghRQSqLSfrkvQnA.jpg",
    release_date: "2008-07-16",
    vote_average: 8.51,
    vote_count: 32000,
    popularity: 130.1,
    adult: false,
    genre_ids: [18, 28, 80, 53],
    runtime: 152,
    tagline: "Welcome to a world without rules.",
    genres: [
      { id: 18, name: "Drama" },
      { id: 28, name: "Action" },
      { id: 80, name: "Crime" },
    ],
  },
  {
    id: 533535,
    title: "Deadpool & Wolverine",
    original_title: "Deadpool & Wolverine",
    overview:
      "A listless Wade Wilson toils away in civilian life with his days as the morally flexible mercenary, Deadpool, behind him. But when his homeworld faces an existential threat, Wade must reluctantly suit-up again with an even more reluctant Wolverine.",
    poster_path: "/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
    backdrop_path: "/yDHYTfA3R0jFYba16jBB1jv8uaC.jpg",
    release_date: "2024-07-24",
    vote_average: 7.7,
    vote_count: 4800,
    popularity: 195.3,
    adult: false,
    genre_ids: [28, 35, 878],
    runtime: 128,
    tagline: "Come together.",
    genres: [
      { id: 28, name: "Action" },
      { id: 35, name: "Comedy" },
      { id: 878, name: "Sci-Fi" },
    ],
  },
  {
    id: 1022789,
    title: "Inside Out 2",
    original_title: "Inside Out 2",
    overview:
      "Teenager Riley's mind headquarters is undergoing a sudden demolition to make room for something entirely unexpected: new Emotions! Joy, Sadness, Anger, Fear and Disgust aren't sure how to feel when Anxiety shows up.",
    poster_path: "/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg",
    backdrop_path: "/stKGOmAUqvKQIUSCTkSt0ugy875.jpg",
    release_date: "2024-06-11",
    vote_average: 7.6,
    vote_count: 4200,
    popularity: 160.0,
    adult: false,
    genre_ids: [16, 10751, 35],
    runtime: 96,
    tagline: "Make room for new emotions.",
    genres: [
      { id: 16, name: "Animation" },
      { id: 35, name: "Comedy" },
    ],
  },
  {
    id: 603,
    title: "The Matrix",
    original_title: "The Matrix",
    overview:
      "Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a underground rebellion against the vast computer that controls human existence by means of a simulated cyber-world.",
    poster_path: "/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    backdrop_path: "/7c9UVPPiTPltouxShY9fEb9MiqT.jpg",
    release_date: "1999-03-30",
    vote_average: 8.21,
    vote_count: 25000,
    popularity: 98.7,
    adult: false,
    genre_ids: [28, 878],
    runtime: 136,
    tagline: "Welcome to the Real World.",
    genres: [
      { id: 28, name: "Action" },
      { id: 878, name: "Sci-Fi" },
    ],
  },
  {
    id: 496243,
    title: "Parasite",
    original_title: "기생충",
    original_language: "ko",
    overview:
      "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
    poster_path: "/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg",
    backdrop_path: "/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg",
    release_date: "2019-05-30",
    vote_average: 8.5,
    vote_count: 17500,
    popularity: 110.4,
    adult: false,
    genre_ids: [35, 53, 18],
    runtime: 132,
    tagline: "Act like you own the place.",
    genres: [
      { id: 35, name: "Comedy" },
      { id: 53, name: "Thriller" },
      { id: 18, name: "Drama" },
    ],
  },
  {
    id: 396535,
    title: "Train to Busan",
    original_title: "부산행",
    original_language: "ko",
    overview:
      "While a zombie virus breaks out in South Korea, passengers struggle to survive on the train from Seoul to Busan.",
    poster_path: "/vVpEOvdxVBP2aV166j5Xlvb5C2f.jpg",
    backdrop_path: "/70AV2Xx5FQYj20labp0EGdbGd4v.jpg",
    release_date: "2016-07-20",
    vote_average: 7.8,
    vote_count: 5800,
    popularity: 95.0,
    adult: false,
    genre_ids: [28, 27, 53],
    runtime: 118,
    tagline: "Life-or-death survival on the high-speed rails.",
    genres: [
      { id: 28, name: "Action" },
      { id: 27, name: "Horror" },
      { id: 53, name: "Thriller" },
    ],
  },
  {
    id: 579974,
    title: "RRR",
    original_title: "RRR",
    original_language: "te",
    overview:
      "A fictional history of two legendary revolutionaries' journey away from home before they began fighting for their country in the 1920s.",
    poster_path: "/nEufeZlyAOLqO2brrs0yeMu1QXO.jpg",
    backdrop_path: "/707thQgf4wQ2Gq2aDqI1gZfW1sO.jpg",
    release_date: "2022-03-24",
    vote_average: 7.8,
    vote_count: 1550,
    popularity: 88.0,
    adult: false,
    genre_ids: [28, 18],
    runtime: 182,
    tagline: "Rise, Roar, Revolt.",
    genres: [
      { id: 28, name: "Action" },
      { id: 18, name: "Drama" },
    ],
  },
  {
    id: 360814,
    title: "Dangal",
    original_title: "दंगल",
    original_language: "hi",
    overview:
      "Dangal is an extraordinary true story based on the life of Mahavir Singh and his two wrestler daughters, Geeta and Babita Phogat.",
    poster_path: "/538U3g2sKqB5k7k5yv7sK3l0w8l.jpg",
    backdrop_path: "/w2toPhKG2Gv4uU6o6hCg4N3aD7y.jpg",
    release_date: "2016-12-23",
    vote_average: 8.0,
    vote_count: 950,
    popularity: 76.0,
    adult: false,
    genre_ids: [18, 28],
    runtime: 161,
    tagline: "Gold is gold, whether won by a boy or a girl.",
    genres: [
      { id: 18, name: "Drama" },
      { id: 28, name: "Action" },
    ],
  },
  {
    id: 872906,
    title: "Jawan",
    original_title: "जवान",
    original_language: "hi",
    overview:
      "A high-octane action thriller outlining the emotional journey of a man set out to rectify the wrongs in society against a vengeful outlaw.",
    poster_path: "/jIjSnvO1mQo5vN2m1Tf4WqO3uO1.jpg",
    backdrop_path: "/qNp3iF9oR6wB6N9gq2i3i3Vp0v1.jpg",
    release_date: "2023-09-07",
    vote_average: 7.2,
    vote_count: 420,
    popularity: 82.0,
    adult: false,
    genre_ids: [28, 53],
    runtime: 169,
    tagline: "Ready chief!",
    genres: [
      { id: 28, name: "Action" },
      { id: 53, name: "Thriller" },
    ],
  },
  {
    id: 569094,
    title: "Spider-Man: Across the Spider-Verse",
    original_title: "Spider-Man: Across the Spider-Verse",
    original_language: "en",
    overview:
      "After reuniting with Gwen Stacy, Brooklyn's full-time, friendly neighborhood Spider-Man is catapulted across the Multiverse, where he encounters the Spider Society.",
    poster_path: "/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg",
    backdrop_path: "/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg",
    release_date: "2023-05-31",
    vote_average: 8.4,
    vote_count: 6700,
    popularity: 240.0,
    adult: false,
    genre_ids: [16, 28, 12, 878],
    runtime: 140,
    tagline: "It's how you wear the mask that matters.",
    genres: [
      { id: 16, name: "Animation" },
      { id: 28, name: "Action" },
      { id: 12, name: "Adventure" },
      { id: 878, name: "Sci-Fi" },
    ],
  },
  {
    id: 634649,
    title: "Spider-Man: No Way Home",
    original_title: "Spider-Man: No Way Home",
    original_language: "en",
    overview:
      "Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous.",
    poster_path: "/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    backdrop_path: "/iQFcwSGbZXMkeyKrxbPnwnRo5fl.jpg",
    release_date: "2021-12-15",
    vote_average: 8.0,
    vote_count: 19800,
    popularity: 220.0,
    adult: false,
    genre_ids: [28, 12, 878],
    runtime: 148,
    tagline: "The Multiverse unleashed.",
    genres: [
      { id: 28, name: "Action" },
      { id: 12, name: "Adventure" },
      { id: 878, name: "Sci-Fi" },
    ],
  },
  {
    id: 299534,
    title: "Avengers: Endgame",
    original_title: "Avengers: Endgame",
    original_language: "en",
    overview:
      "After the devastating events of Infinity War, the universe is in ruins. With the help of remaining allies, the Avengers assemble once more to reverse Thanos' actions.",
    poster_path: "/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
    backdrop_path: "/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg",
    release_date: "2019-04-24",
    vote_average: 8.3,
    vote_count: 25000,
    popularity: 195.0,
    adult: false,
    genre_ids: [12, 878, 28],
    runtime: 181,
    tagline: "Part of the journey is the end.",
    genres: [
      { id: 12, name: "Adventure" },
      { id: 878, name: "Sci-Fi" },
      { id: 28, name: "Action" },
    ],
  },
  {
    id: 155,
    title: "The Dark Knight",
    original_title: "The Dark Knight",
    original_language: "en",
    overview:
      "Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets.",
    poster_path: "/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    backdrop_path: "/nMKdUUepR0i5zn0y1T4CsSB5chy.jpg",
    release_date: "2008-07-16",
    vote_average: 8.51,
    vote_count: 32000,
    popularity: 160.0,
    adult: false,
    genre_ids: [18, 28, 80, 53],
    runtime: 152,
    tagline: "Welcome to a world without rules.",
    genres: [
      { id: 18, name: "Drama" },
      { id: 28, name: "Action" },
      { id: 80, name: "Crime" },
      { id: 53, name: "Thriller" },
    ],
  },
];

export const FALLBACK_TV_SHOWS: TMDBTVShow[] = [
  {
    id: 66732,
    name: "Stranger Things",
    original_name: "Stranger Things",
    overview:
      "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl with telekinetic powers.",
    poster_path: "/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
    backdrop_path: "/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
    first_air_date: "2016-07-15",
    vote_average: 8.6,
    vote_count: 17200,
    popularity: 220.1,
    genre_ids: [18, 10765, 9648],
    number_of_seasons: 4,
    number_of_episodes: 34,
    tagline: "Every ending has a beginning.",
    genres: [
      { id: 18, name: "Drama" },
      { id: 10765, name: "Sci-Fi & Fantasy" },
      { id: 9648, name: "Mystery" },
    ],
    seasons: [
      {
        id: 77680,
        name: "Season 1",
        overview: "Strange things are afoot in Hawkins, Indiana.",
        season_number: 1,
        episode_count: 8,
        poster_path: "/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
        air_date: "2016-07-15",
      },
      {
        id: 90934,
        name: "Season 2",
        overview: "It's 1984 and the citizens of Hawkins are still reeling from the horrors of the Demogorgon.",
        season_number: 2,
        episode_count: 9,
        poster_path: "/lwpEe4Ntc2gZkK9b6tX02M3y3g.jpg",
        air_date: "2017-10-27",
      },
      {
        id: 115216,
        name: "Season 3",
        overview: "It's 1985 in Hawkins, Indiana, and summer's heating up.",
        season_number: 3,
        episode_count: 8,
        poster_path: "/t7Et344yFp5fGv6F3n3hQfE2iH.jpg",
        air_date: "2019-07-04",
      },
      {
        id: 154511,
        name: "Season 4",
        overview: "Darkness returns to Hawkins just in time for spring break.",
        season_number: 4,
        episode_count: 9,
        poster_path: "/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
        air_date: "2022-05-27",
      },
    ],
  },
  {
    id: 1396,
    name: "Breaking Bad",
    original_name: "Breaking Bad",
    overview:
      "Walter White, a New Mexico chemistry teacher, is diagnosed with Stage III cancer and given a prognosis of two years left to live. He chooses to enter a dangerous world of drugs and crime to ensure his family's financial security.",
    poster_path: "/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg",
    backdrop_path: "/9faGSFi5jam6pDWGNdFaF8IRNGP.jpg",
    first_air_date: "2008-01-20",
    vote_average: 8.9,
    vote_count: 14200,
    popularity: 185.0,
    genre_ids: [18, 80],
    number_of_seasons: 5,
    number_of_episodes: 62,
    tagline: "Change the equation.",
    genres: [
      { id: 18, name: "Drama" },
      { id: 80, name: "Crime" },
    ],
    seasons: [
      {
        id: 3572,
        name: "Season 1",
        overview: "Walter White turns to manufacturing methamphetamine.",
        season_number: 1,
        episode_count: 7,
        poster_path: "/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg",
        air_date: "2008-01-20",
      },
      {
        id: 3573,
        name: "Season 2",
        overview: "Walt and Jesse face mounting danger as their operation expands.",
        season_number: 2,
        episode_count: 13,
        poster_path: "/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg",
        air_date: "2009-03-08",
      },
      {
        id: 3574,
        name: "Season 3",
        overview: "Walt tries to balance family life while dealing with Gus Fring.",
        season_number: 3,
        episode_count: 13,
        poster_path: "/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg",
        air_date: "2010-03-21",
      },
    ],
  },
  {
    id: 94605,
    name: "Arcane",
    original_name: "Arcane",
    overview:
      "Amid the stark discord of twin cities Piltover and Zaun, two sisters fight on rival sides of a war between magic technologies and incompatible convictions.",
    poster_path: "/fqldf2t8ztc9aiwn397rWW2vGyL.jpg",
    backdrop_path: "/vhnT3gXlqG6g0f9T0qA8A6Pq6aM.jpg",
    first_air_date: "2021-11-06",
    vote_average: 8.7,
    vote_count: 4100,
    popularity: 135.6,
    genre_ids: [16, 10765, 18],
    number_of_seasons: 2,
    number_of_episodes: 18,
    tagline: "Every legend has a beginning.",
    genres: [
      { id: 16, name: "Animation" },
      { id: 10765, name: "Sci-Fi & Fantasy" },
      { id: 18, name: "Drama" },
    ],
    seasons: [
      {
        id: 134187,
        name: "Season 1",
        overview: "The origins of two iconic League champions, set in the utopian Piltover and the oppressed underground of Zaun.",
        season_number: 1,
        episode_count: 9,
        poster_path: "/fqldf2t8ztc9aiwn397rWW2vGyL.jpg",
        air_date: "2021-11-06",
      },
    ],
  },
  {
    id: 76479,
    name: "The Boys",
    original_name: "The Boys",
    overview:
      "A fun and irreverent take on what happens when superheroes, who are as popular as celebrities, as influential as politicians and as revered as gods, abuse their superpowers rather than use them for good.",
    poster_path: "/7Ns6tO3aYjppI5Lo0Pf9B59yCpd.jpg",
    backdrop_path: "/n5A7br2035I875n75u7g48s5n4u.jpg",
    first_air_date: "2019-07-26",
    vote_average: 8.4,
    vote_count: 10500,
    popularity: 168.0,
    genre_ids: [10759, 10765],
    number_of_seasons: 4,
    number_of_episodes: 32,
    tagline: "Never meet your heroes.",
    genres: [
      { id: 10759, name: "Action & Adventure" },
      { id: 10765, name: "Sci-Fi & Fantasy" },
    ],
    seasons: [
      {
        id: 97893,
        name: "Season 1",
        overview: "When superheroes go rogue, the Boys assemble to take them down.",
        season_number: 1,
        episode_count: 8,
        poster_path: "/7Ns6tO3aYjppI5Lo0Pf9B59yCpd.jpg",
        air_date: "2019-07-26",
      },
    ],
  },
  {
    id: 93405,
    name: "Squid Game",
    original_name: "오징어 게임",
    original_language: "ko",
    overview:
      "Hundreds of cash-strapped players accept a strange invitation to compete in children's games. Inside, a tempting prize awaits with deadly high stakes.",
    poster_path: "/dDlGvlKc08h7Lp8w00hYl6P3NqC.jpg",
    backdrop_path: "/qw3J9cNeLioOL0Ukb6Ns69eBVNI.jpg",
    first_air_date: "2021-09-17",
    vote_average: 7.8,
    vote_count: 14000,
    popularity: 210.0,
    genre_ids: [10759, 9648, 18],
    number_of_seasons: 2,
    number_of_episodes: 15,
    tagline: "45.6 Billion is child's play.",
    genres: [
      { id: 10759, name: "Action & Adventure" },
      { id: 9648, name: "Mystery" },
      { id: 18, name: "Drama" },
    ],
    seasons: [
      {
        id: 131977,
        name: "Season 1",
        overview: "Desperate individuals enter a mysterious survival competition.",
        season_number: 1,
        episode_count: 9,
        poster_path: "/dDlGvlKc08h7Lp8w00hYl6P3NqC.jpg",
        air_date: "2021-09-17",
      },
    ],
  },
  {
    id: 84661,
    name: "Mirzapur",
    original_name: "मिर्ज़ापुर",
    original_language: "hi",
    overview:
      "The iron-fisted Akhandanand Tripathi is a millionaire carpet exporter and the mafia don of Mirzapur, whose son Munna is an unworthy, power-hungry heir.",
    poster_path: "/h306wO5x0Q7b0X0x2y3j0h8X5l2.jpg",
    backdrop_path: "/k7N0w2a2B3x0r4q0p3i7a0X3a2j.jpg",
    first_air_date: "2018-11-16",
    vote_average: 8.3,
    vote_count: 380,
    popularity: 85.0,
    genre_ids: [80, 18, 10759],
    number_of_seasons: 3,
    number_of_episodes: 29,
    tagline: "Rule or be ruled.",
    genres: [
      { id: 80, name: "Crime" },
      { id: 18, name: "Drama" },
      { id: 10759, name: "Action & Adventure" },
    ],
    seasons: [
      {
        id: 112838,
        name: "Season 1",
        overview: "The rise of two brothers in the lawless badlands of Mirzapur.",
        season_number: 1,
        episode_count: 9,
        poster_path: "/h306wO5x0Q7b0X0x2y3j0h8X5l2.jpg",
        air_date: "2018-11-16",
      },
    ],
  },
  {
    id: 1396,
    name: "Breaking Bad",
    original_name: "Breaking Bad",
    original_language: "en",
    overview:
      "Walter White, a New Mexico chemistry teacher, is diagnosed with Stage III cancer and given a prognosis of two years left to live. He chooses to enter the dangerous world of drugs and crime.",
    poster_path: "/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg",
    backdrop_path: "/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg",
    first_air_date: "2008-01-20",
    vote_average: 8.9,
    vote_count: 14500,
    popularity: 190.0,
    genre_ids: [18, 80],
    number_of_seasons: 5,
    number_of_episodes: 62,
    tagline: "Change the equation.",
    genres: [
      { id: 18, name: "Drama" },
      { id: 80, name: "Crime" },
    ],
    seasons: [
      {
        id: 3572,
        name: "Season 1",
        overview: "High school chemistry teacher Walter White's life is turned upside down.",
        season_number: 1,
        episode_count: 7,
        poster_path: "/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg",
        air_date: "2008-01-20",
      },
    ],
  },
  {
    id: 1399,
    name: "Game of Thrones",
    original_name: "Game of Thrones",
    original_language: "en",
    overview:
      "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war while a very ancient evil awakens in the farthest north.",
    poster_path: "/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg",
    backdrop_path: "/2OMB0ynKlyIenMJWI2Dy9IWT4c.jpg",
    first_air_date: "2011-04-17",
    vote_average: 8.45,
    vote_count: 23000,
    popularity: 280.0,
    genre_ids: [10765, 18, 10759],
    number_of_seasons: 8,
    number_of_episodes: 73,
    tagline: "Winter is coming.",
    genres: [
      { id: 10765, name: "Sci-Fi & Fantasy" },
      { id: 18, name: "Drama" },
      { id: 10759, name: "Action & Adventure" },
    ],
    seasons: [
      {
        id: 3624,
        name: "Season 1",
        overview: "Trouble is brewing in the Seven Kingdoms of Westeros.",
        season_number: 1,
        episode_count: 10,
        poster_path: "/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg",
        air_date: "2011-04-17",
      },
    ],
  },
];

export const FALLBACK_EPISODES: Record<string, TMDBSeasonDetail> = {
  "66732-1": {
    id: 77680,
    name: "Season 1",
    overview: "Strange things are afoot in Hawkins, Indiana.",
    season_number: 1,
    poster_path: "/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
    air_date: "2016-07-15",
    episodes: [
      {
        id: 1198642,
        name: "Chapter One: The Vanishing of Will Byers",
        overview:
          "On his way home from a friend's house, young Will sees something terrifying. Nearby, a sinister secret lurks in the depths of a government lab.",
        season_number: 1,
        episode_number: 1,
        still_path: "/w5gV5Zqf8f6tQcT4b0u4Q7Xp8Vw.jpg",
        air_date: "2016-07-15",
        vote_average: 8.3,
        vote_count: 420,
        runtime: 49,
      },
      {
        id: 1198643,
        name: "Chapter Two: The Weirdo on Maple Street",
        overview:
          "Lucas, Mike and Dustin try to talk to the girl they found in the woods. Hopper questions an anxious Joyce about an unsettling phone call.",
        season_number: 1,
        episode_number: 2,
        still_path: "/rJpP0r8g7o7u4V5e2r9f4o5n4.jpg",
        air_date: "2016-07-15",
        vote_average: 8.2,
        vote_count: 360,
        runtime: 56,
      },
      {
        id: 1198644,
        name: "Chapter Three: Holly, Jolly",
        overview:
          "An increasingly concerned Joyce believes Will is communicating with her through Christmas lights. Hopper breaks into Hawkins Lab.",
        season_number: 1,
        episode_number: 3,
        still_path: "/w5gV5Zqf8f6tQcT4b0u4Q7Xp8Vw.jpg",
        air_date: "2016-07-15",
        vote_average: 8.7,
        vote_count: 380,
        runtime: 52,
      },
      {
        id: 1198645,
        name: "Chapter Four: The Body",
        overview:
          "Refusing to believe Will is dead, Joyce tries to connect with her son. The boys give Eleven a makeover so she can sneak into school.",
        season_number: 1,
        episode_number: 4,
        still_path: "/rJpP0r8g7o7u4V5e2r9f4o5n4.jpg",
        air_date: "2016-07-15",
        vote_average: 8.6,
        vote_count: 370,
        runtime: 51,
      },
    ],
  },
  "1396-1": {
    id: 3572,
    name: "Season 1",
    overview: "Walter White turns to manufacturing methamphetamine.",
    season_number: 1,
    poster_path: "/ztkUQFLlC19CCMYHW9o1zWhJRNq.jpg",
    air_date: "2008-01-20",
    episodes: [
      {
        id: 62085,
        name: "Pilot",
        overview:
          "When an unassuming high school chemistry teacher is diagnosed with terminal lung cancer, he decides to secure his family's financial future by cooking crystal meth.",
        season_number: 1,
        episode_number: 1,
        still_path: "/ydlY3iPbg5MNt2k9rX4f6g7v8a.jpg",
        air_date: "2008-01-20",
        vote_average: 8.9,
        vote_count: 550,
        runtime: 58,
      },
      {
        id: 62086,
        name: "Cat's in the Bag...",
        overview:
          "Walt and Jesse attempt to tie up loose ends following the altercation in the desert, but the disposal process quickly goes awry.",
        season_number: 1,
        episode_number: 2,
        still_path: "/ydlY3iPbg5MNt2k9rX4f6g7v8a.jpg",
        air_date: "2008-01-27",
        vote_average: 8.7,
        vote_count: 480,
        runtime: 48,
      },
    ],
  },
};

export const FALLBACK_CREDITS: Record<number, TMDBCredits> = {
  157336: {
    id: 157336,
    cast: [
      { id: 10297, name: "Matthew McConaughey", character: "Joseph Cooper", profile_path: "/eD9XWl97uP2dF7e9eH9gqH9J5m9.jpg" },
      { id: 1813, name: "Anne Hathaway", character: "Dr. Amelia Brand", profile_path: "/tLpq5i9o0X3rN7s4m2v1p4g.jpg" },
      { id: 3895, name: "Michael Caine", character: "Professor Brand", profile_path: "/nlq5eR4b2a8u9V0p1c2.jpg" },
      { id: 83002, name: "Jessica Chastain", character: "Murphy Cooper", profile_path: "/f4u8p0w3c5v8g7x2z9.jpg" },
    ],
    crew: [
      { id: 525, name: "Christopher Nolan", job: "Director", profile_path: "/xuAIuYSmsUzKlUMBFGVZaWsY3Z5.jpg" },
      { id: 947, name: "Hans Zimmer", job: "Original Music Composer", profile_path: "/tp7r5z3m8.jpg" },
    ],
  },
  27205: {
    id: 27205,
    cast: [
      { id: 6193, name: "Leonardo DiCaprio", character: "Dom Cobb", profile_path: "/wo2YrOiTbt2Yb1Q170V79VeqlVO.jpg" },
      { id: 24045, name: "Joseph Gordon-Levitt", character: "Arthur", profile_path: "/z2kd7P9U1.jpg" },
      { id: 27578, name: "Elliot Page", character: "Ariadne", profile_path: "/c5t7k9.jpg" },
      { id: 2524, name: "Tom Hardy", character: "Eames", profile_path: "/d8th8.jpg" },
    ],
    crew: [
      { id: 525, name: "Christopher Nolan", job: "Director", profile_path: "/xuAIuYSmsUzKlUMBFGVZaWsY3Z5.jpg" },
    ],
  },
};

